version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mock-api-server:
    build: .
    container_name: mock-api-server
    restart: always
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - "3002:3002"

volumes:
  mongo_data:
